In [9]:
path = "C:\\Мари\\учеба\\Финансовый университет\\1 курс\\2 семестр\\Технологии обработки данных\\Лабораторная работа 1\\data\\minutes_n_ingredients.csv"

In [10]:
# Задание 1
import numpy as np
arr = np.loadtxt(path, int, skiprows=1, delimiter=',')
arr[:5, :]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

In [12]:
# Задание 2
print("Второй столбец:")
print(np.mean(arr[:, 1]))
print(np.min(arr[:, 1]))
print(np.max(arr[:, 1]))
print(np.median(arr[:, 1]))
print("\nТретий столбец:")
print(np.mean(arr[:, 2]))
print(np.min(arr[:, 2]))
print(np.max(arr[:, 2]))
print(np.median(arr[:, 2]))

Второй столбец:
21601.00169
0
2147483647
40.0

Третий столбец:
9.05528
1
39
9.0


In [13]:
# Задание 3
quan = np.quantile(arr[:, 1], 0.75)
arr[:, 1] = np.where(arr[:, 1] <= quan, arr[:, 1], quan)
print(arr)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [498432     65     15]
 [370915      5      4]
 [ 81993     65     14]]


In [14]:
# Задание 4
print(np.count_nonzero(arr[:, 1] == 0))
arr[:, 1] = np.where(arr[:, 1] != 0, arr[:, 1], 1)

479


In [15]:
# Задание 5
print(len(np.unique(arr[:, 0])))

100000


In [16]:
# Задание 6
print(len(np.unique(arr[:, 2])))
print(np.unique(arr[:, 2]))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


In [17]:
# Задание 7
arr2 = arr[np.where(arr[:, 2] <= 5)]
print(arr2)

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


In [18]:
# Задание 8
ingr_in_minute = arr[:, 2] / arr[: ,1]
print(np.max(ingr_in_minute))

24.0


In [19]:
# Задание 9
sorting = np.array(sorted(arr, key=lambda a_entry: a_entry[1], reverse=True))
print(np.mean(sorting[:100, 2]))

10.03


In [20]:
# Задание 10
idx = np.random.randint(len(arr), size=10)
print(arr[idx, :])

[[210167     30     14]
 [178131     30      5]
 [300982     60     14]
 [ 27393     65     12]
 [ 65985      2      3]
 [313702     35      4]
 [184316     65     18]
 [505841     20     12]
 [ 23647     30     11]
 [289441     65      7]]


In [21]:
# Задание 11
print(len(arr[np.where(arr[:, 2] < np.mean(arr[:, 2]))]) / len(arr) * 100)

58.802


In [22]:
# Задание 12
simple = np.c_[arr, np.zeros(len(arr)).astype(int)]
simple[:, 3] = np.where((arr[:, 1] <= 20) & (arr[:, 2] <= 5), 1, 0)
simple

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

In [23]:
# Задание 13
print(len(simple[np.where(simple[:, 3] == 1)]) / len(simple) * 100)

9.552


In [24]:
# Задание 14
duration = np.array([np.zeros(len(arr)).astype(int), arr[:, 0], simple[:, 3]]).transpose()
duration[:, 0] = np.where((arr[:, 1] >= 10) & (arr[:, 1] < 20), 1, duration[:, 0])
duration[:, 0] = np.where(arr[:, 1] >= 20, 2, duration[:, 0])
duration

array([[     2, 127244,      0],
       [     2,  23891,      0],
       [     1,  94746,      0],
       ...,
       [     2, 498432,      0],
       [     0, 370915,      1],
       [     2,  81993,      0]])